### ISSUE TITLE
Feature request: context menu for properties

### ISSUE THREAD

**Issue by chulanovskyi** [anboralabs/intellij-ngrok#15]
Hello there! 
Could you please add a context menu with an option of copying to the clipboard the value of the property:

![image](https://user-images.githubusercontent.com/13966263/204004939-63c80b78-074f-476c-8b90-9d7ffd0c6c34.png)

I know, that if I simply use "ctrl + c / v" it will give me the following:

`Url	https://07e5-92-253-236-70.ngrok.io`

But then I would have to clean the `Url` prefix manually, in order to have the url itself... 

Not urgent, it would just improve the overall UX. Thank you in advance 👍🏻

**Comment by dalgarins** [comment]
@chulanovskyi next version 2024.3.2 will fix this, copy action only will copy values.

**Comment by dalgarins** [comment]
@chulanovskyi test it and let me know if it works.

**Comment by chulanovskyi-bs** [comment]
@dalgarins Hi there! Thanks. I'm trying it on Windows, however nothing but "Connected" I can't see in the service tab. In the "Edit configuration" I've provided an API token, and that is it. Any clue?)

![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/b941e3de-90d2-40f2-ba59-06a3468a39d0)

**Comment by chulanovskyi-bs** [comment]
![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/cb23dd90-91c4-4f73-9d6d-15b989747d47)

**Comment by chulanovskyi-bs** [comment]
Do you mean here? Unfortunately, there is no other `ngrok` config, except the one that I've shared previously, which is ngrok host

![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/6b735bcb-282b-4442-9c90-6c41f70554a8)

![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/b4d18b3e-7ea1-4e3a-b374-d5a985fcf979)

That ngrok host has the following config:

![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/cb34080f-48d2-4ea3-80ef-06c5717cb995)


In Settings there is not much for the Ngrok:

![image](https://github.com/anboralabs/intellij-ngrok/assets/56116665/835393e1-0302-41a6-a2ab-7391ff68330f)

**Comment by dalgarins** [comment]
@chulanovskyi here: 

![Screenshot 2024-04-29 at 12 36 14 PM](https://github.com/anboralabs/intellij-ngrok/assets/8527174/62b361f4-5856-4530-b40e-3d5e356e3861)

![Screenshot 2024-04-29 at 12 36 38 PM](https://github.com/anboralabs/intellij-ngrok/assets/8527174/49770bc2-b323-4c11-88c4-9c445ca0fa1e)

**Comment by chulanovskyi-bs** [comment]
Silly me 🙂 forgot how to use that tool. Yep, `ctrl+c` -> `ctrl+v` works for copying values. Case closed
