### ISSUE TITLE
docs: Add step-by-step instructions

### ISSUE THREAD

**Issue by Swimburger** [anboralabs/intellij-ngrok#3]
We're excited about this plugin but struggled to figure out how to use it.
We eventually found that you have to create a run configuration, and once you do that, you can start the ngrok application, and then right-click on the application to create a tunnel under the services tab.

This isn't very discoverable however, so it'd be great if there was more documentation on how to use the plugin.
I'd be happy to help in that regard.

**Comment by dalgarins** [comment]
@Swimburger thank you, you are right, which do you think is the best way to create a tutorial? where do you want to see it? in the plugin page? if you want to contribute please create the tutorial and I'll publish in the main page. what do you think?

**Comment by Swimburger** [comment]
Is the most optimal path the following?

- Edit Configurations...
  - Add New Configuration -> Ngrok
  - Select or create Server
  - Click OK
- Open Services Tool Window
  - Find your Ngrok Run configuration under Services > Ngrok > Not Started > Ngrok Run, and run it
  - Find your Ngrok Application under Services > Ngrok > Ngrok Application, and click "Add Tunnel"
    - Enter tunnel information and click OK

**Comment by dalgarins** [comment]
Thanks a lot, I will add this and I will also create a video to show how to use it. I'll let you know and ask you for feedback.

**Comment by dalgarins** [comment]
@Swimburger added a video an simple documentation for the plugin. thanks a lot.

**Comment by Swimburger** [comment]
Great! Where can we find this video?
