### ISSUE TITLE
Not able to tunnel HTTPS URL

### ISSUE THREAD

**Issue by Swimburger** [anboralabs/intellij-ngrok#4]
When you run ngrok from using the CLI, you can specify HTTPS URLs (when authenticated):
```bash
ngrok http https://localhost:8080
```

In the plugin, you can only specify a port when selecting HTTP and HTTPS is not an option.

It'd be great if we could select HTTPS, or specify the entire URL like the CLI command.

**Comment by hubseven** [comment]
This is a great plug-in thank you for your work. I too would like to see this feature to be able to add a host here
![image](https://user-images.githubusercontent.com/5764633/206754240-71b15881-9515-4d9a-88fe-5aa6a8c353f9.png)

Thank you

**Comment by dalgarins** [comment]
<img width="448" alt="Captura de Pantalla 2022-12-12 a la(s) 1 48 49 p m" src="https://user-images.githubusercontent.com/8527174/207129917-44e45c0b-b66d-4495-9b08-50d71d8144ba.png">

this feature will be released on version: 1.3.0
