### ISSUE TITLE
The ngrok process was unable to start

### ISSUE THREAD

**Issue by karinerock** [anboralabs/intellij-ngrok#45]
I'm trying to run the plugin on my Jetbrain Webstorm IDE, but for some unknown reason, it does not seems to work.
I have a leggit license.
I have a leggit Jetbrains account
I have followed the strep in the demo installation video.
I still get this error (all the time).

OS: MacOS 14.3
Webstorm: 2023.3.5 (latest for my OS I guess)
Plugin version: 2023.3.1

![Screenshot 2024-03-15 at 3 08 02 PM](https://github.com/anboralabs/intellij-ngrok/assets/72523330/35c5c97f-68fb-4b9d-9de8-ab77eb9d685a)

Please let me know what I'm missing?

**Comment by dalgarins** [comment]
@karinerock you have an intel or m1 mac? the plugin show any other issue? a notification or something? I will install the same version you have and validate what is happening.

**Comment by dalgarins** [comment]
@karinerock could you try reinstalling the plugin?

**Comment by karinerock** [comment]
> @karinerock you have an intel or m1 mac? the plugin show any other issue? a notification or something? I will install the same version you have and validate what is happening.

Mac BookPro Intel.
No other issue (visible)
No notifications
I have tried reinstalling many times, but still the same behavior ...

**Comment by dalgarins** [comment]
@karinerock I have added an option to setup a ngrok client

<img width="424" alt="Screenshot 2024-03-23 at 5 05 06 PM" src="https://github.com/anboralabs/intellij-ngrok/assets/8527174/53937e93-e8b0-438b-80c8-90d2ddb26eef">
<img width="972" alt="Screenshot 2024-03-23 at 5 05 31 PM" src="https://github.com/anboralabs/intellij-ngrok/assets/8527174/c51312ca-3e90-4fb4-afe3-67b7a0470d15">

could you install from releases in this repo or wait for update on marketplace: 2024.3.1

**Comment by dalgarins** [comment]
@karinerock the new version is available on marketplace, could you test it? And let me know if your issue was fixed, thanks a lot.

**Comment by karinerock** [comment]
> @karinerock the new version is available on marketplace, could you test it? And let me know if your issue was fixed, thanks a lot.

Ok, thanks a lot, I will try this and let your know the result

**Comment by dalgarins** [comment]
@karinerock any updates?

**Comment by dalgarins** [comment]
@karinerock I will close the issue.

**Comment by karinerock** [comment]
> @karinerock any updates?

It's working great now!! Thanks a lot for the support!
