### ISSUE TITLE
Add additional configuration -host-header

### ISSUE THREAD

**Issue by karinerock** [anboralabs/intellij-ngrok#52]
Thanks for your updated version 2024.3.1 which I was able to run as a service in my IDE Webstorm.

So, far, I am unable to run my app in dev mode through, since the host-header needs to be specific in order for the oauth app so securely authorize my host to call the API. Would it be possible to add the extra property host-header in the config section? That would actualily enable me to finally use this plugins in my IDE (instead of the CLI setup line in my terminal).

**Comment by dalgarins** [comment]
Ok, I will work on that

**Comment by dalgarins** [comment]
<img width="456" alt="Screenshot 2024-04-27 at 5 43 30 PM" src="https://github.com/anboralabs/intellij-ngrok/assets/8527174/802e608f-bbf0-40d3-87a3-d0e5c77b5ca8">

this feature will be available on version 2024.3.2, next week will be available.
